### ISSUE TITLE
关于Genuine OJ的一个小问题

### ISSUE THREAD

**Issue by saf-D** [genuine-oj/frontend#16]
您好 两位（群发的）
Genuine OJ
的开发者。
很高兴能看到[这篇Blog](https://www.yixiangzhilv.com/docs/genuine-oj/introduction.html)，也很高兴我正好有个服务器。

很感谢Genuine OJ这个模板，真的很好看。

然鹅，当我千辛万苦的搭好了OJ（搭建并非易事，并不自动化），遇到一个小问题。

我尝试更改前端opt/oj/frontend-naive/src/pages里的vue时（更改成功了），但是网页并没生效。

如我更改了一下注册的一些语言：

![image _8_.png](http://61.186.173.89:2019/2023/08/05/9a0e120267bcf.png)

![image _6_.png](http://61.186.173.89:2019/2023/08/05/6b5f0e3c394e1.png)

但是网页并没生效

后台也没报错。。。

还有一件小请求，能不能加一个插件功能，然后所有人都可以上传，插件中可以写《一键导入很多很多xml、json、txt等格式题目》、《LaTeX优化》、《题目中代码高亮》、《一键回到顶部》、《讨论》、《私信》、《反馈、举报》等等。
因为现在做得并不好不太好：

![](http://61.186.173.89:2019/2023/08/05/6b5f0e3c394e1.png)

![](http://61.186.173.89:2019/2023/08/05/ea15c778cdced.png)

![](http://61.186.173.89:2019/2023/08/05/f42b6afc7c15e.png)

![image _3_.png](http://61.186.173.89:2019/2023/08/05/4a04cfe9108f5.png)

![image _2_.png](http://61.186.173.89:2019/2023/08/05/8aa4d68963c95.png)

![image _1_.png](http://61.186.173.89:2019/2023/08/05/87f332d4d07b3.png)

![image.png](http://61.186.173.89:2019/2023/08/05/f983896891e70.png)

虽然

![image _9_.png](http://61.186.173.89:2019/2023/08/05/2c78e3cdcdf99.png)

并且首页也很鸡肋。

希望Genuine OJ能越做越好！

我是个小LJ，不太会写，我的Github:[saf-D](https://github.com/saf-D)，我的QQ：dkx.111@qq.com(3174969879)，我们的网站（还没绑定域名，刚弄好）：[首页 - INTA-OJ](http://120.53.22.163/)

谢谢你们！

希望我的问题能够很快得到解决qwq。

**Comment by yang-zhongtian** [comment]
已联系您
